# Generated by Django 2.1.3 on 2018-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_api', '0002_clanwar_total_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanhistory',
            name='region_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
