# Generated by Django 2.1.7 on 2019-04-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react_api', '0003_clanhistory_region_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='identifier',
        ),
        migrations.AddField(
            model_name='playerseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='react_api.LeagueSeason'),
        ),
    ]
