# Generated by Django 2.1.7 on 2019-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_api', '0004_auto_20190402_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanhistory',
            name='global_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanhistory',
            name='local_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanhistory',
            name='prev_global_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanhistory',
            name='prev_local_rank',
            field=models.IntegerField(null=True),
        ),
    ]
