# Generated by Django 2.2 on 2019-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_api', '0006_auto_20190405_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullRefresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('error', models.TextField(null=True)),
                ('constants_updated', models.BooleanField()),
                ('clans_count', models.IntegerField()),
                ('players_count', models.IntegerField()),
            ],
        ),
    ]
