# Generated by Django 2.2 on 2019-04-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_api', '0007_fullrefresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullrefresh',
            name='success',
        ),
    ]
