version: '3'

services:
  front:
    build: ./front
    working_dir: /code/front
    volumes:
      - .:/code
    restart: 'no'
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/code
    restart: on-failure
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - front
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - front
      - nginx