version: '3'

services:
  front:
    command: npm run-script build
  web:
    #environment:
    #  - DJANGO_SETTINGS_MODULE=coach_royale.settings_prod
    command: >
      bash -c "cron && python3 manage.py migrate
      && gunicorn3 coach_royale.wsgi:application --bind 0.0.0.0:8000 --error-logfile /code/logs/gunicorn-error.log"