version: '3'

services:
  front:
    build: ./front
    working_dir: /code
    volumes:
      - ./front/dist:/code/dist
    restart: 'no'
  postgres:
    container_name: db.postgres
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=coach_royale
    expose:
      - "5432"
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/code
      - ./logs:/logs
    restart: on-failure
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - front
  web:
    build: .
    volumes:
      - .:/code
      - ./logs:/logs
    #  - ./docker/crontab:/etc/cron.d/coach_royale
    expose:
      - "8000"
    depends_on:
      - front
      - nginx
      - postgres
volumes:
  postgres: