version: '3'

services:
  front:
    command: npm run-script build-dev
  web:
    command: >
        bash -c "cron && python3 manage.py makemigrations && python3 manage.py migrate
        && python3 manage.py runserver 0.0.0.0:8000"
  postgres:
    ports:
      - "127.0.0.1:5432:5432"