version: '3'

services:
  front:
    command: npm run-script build
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=cycom_esport2.settings_prod
    command: gunicorn3 cycom_esport2.wsgi:application --bind 0.0.0.0:8000