version: '3'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=cycom_esport2.settings_prod
    command:  gunicorn3 cycom_esport2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db