version: '3'

services:
  nginx:
    volumes:
    - ./docker/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    - .:/code
    - ./logs:/logs

  backend:
    #environment:
    #  - DJANGO_SETTINGS_MODULE=coach_royale.settings_prod
    command: /code/start-backend.sh
    depends_on:
      - postgres
      - redis
      - nginx