# Generated by Django 3.0.2 on 2020-03-02 22:47

import backend.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0013_playercube'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClanRuleGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', backend.models.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ('applies_to', models.CharField(choices=[('member', 'Member'), ('elder', 'Elder'), ('coLeader', 'Co-Leader')], max_length=16)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Clan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerClanRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', backend.models.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ('field', models.CharField(max_length=128)),
                ('operator', models.CharField(choices=[('>', 'is greater than'), ('<', 'is less than'), ('between', 'is between'), ('not_between', 'is not between')], max_length=32)),
                ('value', models.CharField(max_length=255, null=True)),
                ('value_bound', models.CharField(max_length=255, null=True)),
                ('value_type', models.CharField(choices=[('int', 'int'), ('str', 'str'), ('date', 'date')], default='int', max_length=255)),
                ('is_promoting_rule', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan_rule_matcher.PlayerClanRuleGoal')),
                ('predicate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan_rule_matcher.PlayerClanRule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
