# Generated by Django 3.0.4 on 2020-04-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan_rule_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclanrulegoal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='playerclanrulegoal',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerclanrule',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clan_rule_matcher.PlayerClanRuleGoal'),
        ),
        migrations.AlterField(
            model_name='playerclanrule',
            name='operator',
            field=models.CharField(choices=[('>', 'is greater than'), ('<', 'is less than'), ('between', 'is between')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playerclanrule',
            name='value_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'str'), ('date', 'date'), ('interval', 'interval')], default='int', max_length=255),
        ),
    ]
