# Generated by Django 3.0.7 on 2020-10-19 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_rule_matcher', '0002_auto_20200423_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerclanrulegoal',
            name='applies_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('member', 'Member'), ('elder', 'Elder'), ('coLeader', 'Co-Leader')], max_length=16), size=None),
        ),
        migrations.AlterField(
            model_name='playerclanrule',
            name='operator',
            field=models.CharField(choices=[('>', 'is greater than'), ('<', 'is less than'), ('=', 'is exactly'), ('between', 'is between')], max_length=32),
        ),
    ]
