version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
      - image: circleci/postgres:10.5-alpine-ram
        environment:
          POSTGRES_USER: coach_royale
          POSTGRES_DB: test_coach_royale
      - image: circleci/redis
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mv coach_royale/settings.example.py coach_royale/settings.py
            yarn install
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Linter
          command: |
            . venv/bin/activate
            python3 -m flake8
      - run:
          name: UnitTest
          command: |
            . venv/bin/activate
            coverage run manage.py test --noinput
            coverage report
      - run:
          name: jest
          command: yarn run test && yarn run coverage
      - store_artifacts:
          path: test-reports
          destination: tr1
      - store_test_results:
          path: test-reports
      - run:
          name: Code coverage
          command: |
            . venv/bin/activate
            codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build