# Generated by Django 2.2 on 2019-04-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_fullrefresh_success'),
    ]

    operations = [
        migrations.DeleteModel(name='Arena')
    ]
