# Generated by Django 2.2.7 on 2019-11-13 18:41
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0009_remove_arena_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclanwar',
            name='final_battles_misses',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE
                    backend_playerclanwar
                SET
                    final_battles_misses = CASE
                        WHEN final_battles_done > 0 THEN 0
                        ELSE 1
                    END
                WHERE
                    final_battles_misses IS NULL
            """,
            reverse_sql=""
        )
    ]
