# Generated by Django 3.0.2 on 2020-03-02 22:47

from django.db import migrations, models

from backend.models import PlayerCube


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0012_playerclanstatshistory_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clan_role', models.CharField(max_length=32)),
                ('clan_name', models.CharField(max_length=255)),
                ('joined_clan', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('total_donations', models.IntegerField()),
                ('trophies', models.IntegerField()),
                ('highest_trophies', models.IntegerField()),
                ('challenge_cards_won', models.IntegerField()),
                ('tourney_cards_won', models.IntegerField()),
                ('cards_found', models.IntegerField()),
                ('favorite_card', models.CharField(max_length=128)),
                ('arena', models.IntegerField()),
                ('total_games', models.IntegerField()),
                ('tournament_games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('win_3_crowns', models.IntegerField()),
                ('current_clan_rank', models.IntegerField()),
                ('previous_clan_rank', models.IntegerField()),
                ('donations_this_week', models.IntegerField()),
                ('donations_received_this_week', models.IntegerField()),
                ('wars_participated', models.IntegerField()),
                ('total_final_battles_available', models.IntegerField()),
                ('final_battles_done', models.IntegerField()),
                ('final_battles_missed', models.IntegerField()),
                ('final_battles_lost', models.IntegerField()),
                ('final_battles_won', models.IntegerField()),
                ('missed_ratio', models.FloatField()),
                ('won_ratio', models.FloatField()),
                ('lost_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'backend_playercube',
                'managed': False,
            },
        ),
    ]
