# Generated by Django 3.0.3 on 2020-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200315_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercardlevel',
            name='last_refresh',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playercardlevel',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
