# Generated by Django 3.0.3 on 2020-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200320_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanhistory',
            name='region_id',
            field=models.IntegerField(null=True),
        ),
    ]
