# Generated by Django 3.0.3 on 2020-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200320_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullRefresh',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentRefresh',
        ),
    ]
