# Generated by Django 3.0.4 on 2020-04-17 22:32

import backend.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200413_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=backend.models.fields.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
