# Generated by Django 3.0.7 on 2020-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200622_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanhistory',
            name='clan_war_trophies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanwar',
            name='fame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanwar',
            name='finish_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanwar',
            name='is_river_race',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clanwar',
            name='repair_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerclanwar',
            name='fame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerclanwar',
            name='repair_points',
            field=models.IntegerField(default=0),
        ),
    ]
