# Generated by Django 3.0.7 on 2020-09-19 19:59

from django.db import migrations

from backend.models import PlayerCube


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20200919_1941'),
    ]

    operations = [
        PlayerCube.migrate()
    ]
