# Generated by Django 3.0.7 on 2020-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200919_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemode',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clanwar',
            name='competitors_count',
            field=models.IntegerField(default=5),
        ),
    ]
