# Generated by Django 3.0.7 on 2020-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20201003_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='war_processing_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('failure', 'failure')], default='pending', max_length=64),
        ),
        migrations.RunSQL(
            "UPDATE backend_battle SET war_processing_status = 'processed' WHERE war_id IS NOT NULL;",
            reverse_sql=""
        )
    ]
