# Generated by Django 3.0.7 on 2020-10-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_battle_war_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanwar',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
