# Generated by Django 3.0.10 on 2020-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_battle_war_processing_status'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE backend_clanwar ALTER COLUMN finish_time TYPE TIMESTAMP USING date_start + INTERVAL '1 week'",
            reverse_sql="ALTER TABLE backend_clanwar ALTER COLUMN finish_time TYPE INT USING 0"
        )
    ]
