export const images = {
    trophy: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0226.png",
    swordBlue: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0990.png",
    swordRed: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0989.png",
    cardsGold: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0705.png",
    star: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0703.png",
    exportDeck: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0711.png",
    copyDeck: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0431.png",
    cardCommon: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0713.png",
    playerTimes: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0790.png",
    playerPlus: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0793.png",
    battle2v2: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0810.png",
    coin: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0397.png",
    war: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0972.png",
    level: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0058.png",
    battle: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0277.png",
    battleAlt: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0526.png",
    levelBig: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0312.png",
    magnifyingGlass: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0327.png",
    challenge: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0328.png",
    cwWarYet: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0356.png",
    cwWarLoss: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0357.png",
    swordSmall: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0359.png",
    cardsDown: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0432.png",
    swordUp: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0433.png",
    trophyRibbon: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0460.png",
    trophyLaurels: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0354.png",
    draftMode: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0467.png",
    cards: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0496.png",
    crown: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0507.png",
    cardsStar: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0520.png",
    cwCards: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0594.png",
    social: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0597.png",
    socialAlt: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0624.png",
    battleLog: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0630.png",
    battle2v2Small: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0650.png",
    gear: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_1024.png",
    legendaryTrophy: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0670.png",
    clanTrophy: "https://raw.githubusercontent.com/smlbiobot/cr-ui/master/ui-trim/ui_sprite_0676.png",
    arenaX: (i) => { return "https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/arenas/arena" + Number(i).toString() + '.png'},
    leagueX: (i) => { return "https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/arenas/league" + Number(i).toString() + '.png'},
    regionIcon: (region) => { return "https://raw.githubusercontent.com/hjnilsson/country-flags/master/png100px/" + region + '.png' },
};
